import { expect, test } from '@playwright/test'
import { authenticate, mockHermesApi, TEST_ACCESS_KEY } from './fixtures'

test.beforeEach(async ({ page }) => {
  await authenticate(page, TEST_ACCESS_KEY, 'research')
  await mockHermesApi(page)
  await page.route('**/api/studio/sessions/hermes/groups**', route => route.fulfill({ json: { groups: [], included: [] } }))
})

test('opens account controls from chat without navigating and keeps nested dialogs usable', async ({ page }, testInfo) => {
  await page.goto('/#/hermes/chat')
  const account = page.locator('.page-sidebar-account-btn')
  const menu = page.locator('.sidebar-account-menu')
  await expect(account).toContainText('playwright')
  await account.click()
  await expect(page).toHaveURL(/#\/hermes\/chat$/)
  await expect(menu).toBeVisible()
  await expect(menu.getByTestId('profile-selector-select')).toContainText('research')
  await expect(menu.locator('.model-trigger')).toBeVisible()
  await expect(menu.locator('.language-switch')).toContainText('English')
  await expect(menu.locator('.version-text')).toContainText('Studio v0.5.23')
  await expect(menu.getByRole('button', { name: /Sign Out/ })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('account-menu.png'), animations: 'disabled' })

  await menu.getByTestId('profile-selector-select').click()
  await expect(menu).not.toBeVisible()
  const profiles = page.locator('.profile-manager-modal')
  await expect(profiles).toBeVisible()
  await profiles.locator('.n-base-close').click()
  await expect(profiles).not.toBeVisible()

  await account.click()
  await menu.locator('.model-trigger').click()
  await expect(menu).not.toBeVisible()
  const models = page.getByRole('dialog')
  await expect(models.locator('.model-list')).toBeVisible()
  await models.locator('.n-base-close').click()

  await account.click()
  await menu.locator('.version-text').click()
  await expect(menu).not.toBeVisible()
  await expect(page.locator('.changelog-list')).toBeVisible()
  await page.keyboard.press('Escape')

  await account.click()
  await menu.getByRole('button', { name: 'Settings', exact: true }).click()
  await expect(page).toHaveURL(/#\/hermes\/settings$/)
  await expect(page.getByRole('heading', { name: 'Settings', exact: true })).toBeVisible()
  await expect(menu).not.toBeVisible()
})

for (const path of ['history', 'workflow', 'group-chat']) {
  test(`shares the account entry in ${path}`, async ({ page }) => {
    await page.goto(`/#/hermes/${path}`)
    if (path === 'group-chat') await page.getByRole('dialog').getByRole('button', { name: 'Confirm', exact: true }).click()
    const account = page.locator('.page-sidebar-account-btn')
    await expect(account).toContainText('playwright')
    await account.click()
    await expect(page.locator('.sidebar-account-menu')).toBeVisible()
    await expect(page).toHaveURL(new RegExp(`#/hermes/${path}$`))
    await account.click()
    await expect(page.locator('.sidebar-account-menu')).not.toBeVisible()
  })
}

test('supports keyboard dismissal and collapsed settings sidebar', async ({ page }) => {
  await page.goto('/#/hermes/settings')
  const account = page.locator('.page-sidebar-account-btn')
  await account.focus()
  await page.keyboard.press('ArrowUp')
  await expect(page.locator('.sidebar-account-menu')).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(account).toBeFocused()
  await expect(account).toHaveAttribute('aria-expanded', 'false')
  await page.locator('aside.sidebar .collapse-btn').click()
  await account.click()
  await expect(page.locator('.sidebar-account-menu .model-selector')).toBeVisible()
  await expect(page.locator('.sidebar-account-menu')).toBeInViewport()
})

test('keeps the menu and language selection within a narrow viewport', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 390, height: 680 })
  await page.goto('/#/hermes/settings')
  await page.getByRole('button', { name: 'Menu', exact: true }).click()
  await page.locator('.page-sidebar-account-btn').click()
  const menu = page.locator('.sidebar-account-menu')
  await expect(menu).toBeInViewport()
  await menu.locator('.language-switch').click()
  await page.locator('.n-base-select-option').filter({ hasText: /^简体中文$/ }).click()
  await expect(menu.getByRole('button', { name: '设置', exact: true })).toBeVisible()
  await expect(page.locator('.n-base-select-menu')).not.toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('account-menu-mobile-zh.png'), animations: 'disabled' })
  await menu.getByRole('button', { name: '设置', exact: true }).click()
  await expect(page.locator('aside.sidebar')).not.toHaveClass(/\bopen\b/)
})

test('updates sidebar identity immediately after changing account details', async ({ page }) => {
  await page.route('**/api/auth/change-username', route => route.fulfill({ json: { success: true } }))
  await page.goto('/#/hermes/settings')
  const account = page.locator('.page-sidebar-account-btn')
  await page.getByRole('button', { name: 'Change Username', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.locator('input[type="password"]').fill('fixture-password')
  await dialog.locator('input:not([type="password"])').fill('renamed-account')
  await dialog.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(account).toContainText('renamed-account')
  await page.getByRole('button', { name: 'Generate Random', exact: true }).click()
  await expect(account.locator('img')).toHaveAttribute('src', /^data:image\/svg\+xml;base64,/)
})
